# コラム1（消費者行動研究の系譜概観） {#consumer}

市場を構成する重要なプレイヤーである消費者がどのような行動を取るのかという点もマーケティングにおいて重要な問題である。そのため、マーケティングリサーチでは、消費者を対象にした調査を行うことも多い。また、このような消費者の行動を捉えることに集中した研究領域を消費者行動（論）という。

ここでは、消費者行動研究の3つの主要な系譜を紹介する。第1に1950年代に盛んに行われた消費者の購買動機の探求である。これは、消費者がなぜ製品を購買するのかという疑問から出発した研究アプローチである。なぜ購買したのかという点は消費者の理解のためにとても重要だが、直接的な観測や測定が困難である。そのためこの系譜では、モチベーションリサーチと言われる、消費者の前意識・潜在意識や無意識といった深層心理へ接近するための精神分析学的手法による調査研究が行われてきた。例えば、深層面接法というある事柄についての深層心理を探り出すための個別面接の技法や、投影法と呼ばれる、表面化しにくい消費者の観念や感情を回答に投影させる技法が用いられてきた。しかしながら、方法論的な問題点が指摘されることであまりこのアプローチが採用されることは少なくなった。最も大きな問題は、分析の結果が調査者の能力や直感に依存してしまうことである。これは分析に内包する恣意性を排除できないという大きな問題として指摘された。
また、調査にかかる時間と費用が非常に高いことも実践上の問題であった。アンケート調査などに比べ、各回答者に対する調査コストが高く、調査回答者数の確保が困難であることも本アプローチの障害となった。

次のアプローチは、消費者行動の測定と分析、予測である。このアプローチでは、消費者の観察可能な行動に着目し、消費者の選択行動などを定量的に分析しその結果を用いた行動の予測を行う。このような枠組みは刺激に対する反応に注目するため、消費者行動研究領域では、S(Stimulus)-R(Response)アプローチと言われる。このアプローチの最初期には、調査会社や新聞社によって設置された買い物日記式の消費者パネルデータを用いて分析が行われていた。まず、調査に継続参加する消費者に、いつ、どこで、何を買ったかという購買データを記録させる。そして日記データを製品カテゴリー別に購買履歴データとして加工することで、選択に関する分析が可能であった。このアプローチは1960年代から特に盛んになり、その後ブランド選択行動を確率モデルによって定式化するアプローチが隆盛した。特に、選択行動の分析結果から製品の選択確率（選択のサレやすさ）や市場シェアを予測することも可能になったことや、消費者の個別取引などのデータが普及したことから様々な計量モデルへと発展した。なぜ買うかという頭のなかで起きていることは研究者にとっては観察不可であるため、このアプローチでは分析対象を「観察可能」な顕在的行動に限定し、定量的に研究を行おうと試みている。また、このアプローチの発展においては経済学、オペレーションズ・リサーチ（OR）分野の影響が強く、近年のマーケティング・サイエンス分野への発展と応用につながっている。なお本アプローチの詳細や理論的前提については \@ref(choice) 章にて説明する。

顕在的行動に着目したアプローチが発展する一方で、1970年代以降、心理学の発展を受け、行動の前提となる「態度」などの消費者の内的なプロセスの解明のためのアプローチも盛んになった。これは、消費者の顕在的な行動の前提となる原因が、（頭の中の）心理的プロセスとして検証可能であるとするアプローチであり、S-Rアプローチが心理的・内的なプロセスをブラックボックスとして扱っていたことを問題視する形で、心理学分野における学習理論、認知理論や探索理論の発展に伴い、有力な理論枠組みとして扱われるようになった。この枠組みはS-O (Organism)-Rアプローチと言われ、ここではどうして購買に至るのかという消費者の情報処理プロセスに注目している。特に、このアプローチでは、人間（消費者）を１つの情報処理システムとして捉え、情報の探索、取得、解釈、統合する内的な情報処理プロセスに焦点を当てている。このアプローチは、認知心理学の影響を強く受けており、近年の消費者行動研究の中心的なアプローチである。本書の中では、アンケート設計（\@ref(survey)）や因子分析（\@ref(factor)）、価格感度測定（\@ref(psm)）などで、心理学的な知識を用いた議論や手法を紹介する。


## 参考文献
青木幸弘（2010）『消費者行動の知識』, 日本経済新聞出版社.

池尾恭一, 青木幸弘, 南知惠子, 井上哲浩（2010）『マーケティング』, 有斐閣.