# コラム2-1（マーケティングにおける因果推論導入） {#causation1}

近年の学術的なマーケティング研究では、因果効果を識別することの重要性が高まり、採用されるアプローチについても大きな変化が生じている。2000年代から2010年代前半までのマーケティング研究では、質問紙調査によって収集したデータを、共分散構造分析（Structural Equation Model; SEM）によって分析するという方法が多く取られていた。SEMでは一般的に、観測可能な変数（質問尺度）の背景にある構成概念同士の関係をパス図として示し、その相関関係を計測することでそのパス図の尤もらしさをチェックするという方法が取られた。しかしながら、2010年代後半以降、トップジャーナルに掲載される研究を中心に、特定の変数間の関係についてその因果関係を識別するという目的のもと分析を行うアプローチが主流になってきている。

実務的にも、因果関係の着目は重要になりつつある。マーケティング活動(プロモーション等)の効果を特定するのは意外と難しい。例え、「プロモーションを実施した年度の売上と、その前年度の売上を比較する」といった分析を行うことでプロモーション効果を捉えようとするかもしれない。しかし、前年比ではきちんとプロモーションの効果を抽出できていないかもしれない。この点を理解するために、相関関係と因果関係を区別することが重要になる。

相関関係とは、2 つの変数 $X$ と $Y$ の間に、比例や反比例といった関係があることを指す。一方で因果関係ではどちらが先行要因であるかという前後関係が重要視される。具体的には、要因$X$を変化させることで要因$Y$が変化する時、$X$を原因で$Y$を結果とする因果関係があるという（立森, 2016）。つまり、$X$ が変化した「から」 $Y$ が変化したという関係が因果関係であると言える。

相関関係を因果関係とを区別して認識するためには、主に以下の 2 つの可能性に注意が必要である（中室・津川, 2017）。ここで、仮に企業の年間広告支出額と年間売上との間に正の相関関係が確認できたとする。その際に気をつけるべき1つめの可能性は「逆方向の因果」である。これは、売上が高いから広告支出ができているという因果関係である。この場合、想定とは逆の因果が成立しており、成果が高く余力がある企業が広告に投資できる状態だと解釈でき、広告によって売上が上がるという状況ではない。2 つめの可能性は交絡因子の存在による「疑似相関」である。第3の要素が因果関係を構成する要素の両方に影響を与える場合、その第3の要素を「交絡因子」と言う。例えば、広告と売上の両方に影響を与える別の要素（例えば企業の志向など）が存在している場合、そのような志向を持つ企業が高い広告支出と売上を観測しており、広告と売上との間に因果関係があるかのように見せているかもしれない。このように、本当は因果関係がないのに交絡因子によって観察される相関関係のことを疑似相関と呼ぶ。

ただし、「真の因果効果」なるものは我々の頭の中にしか存在せず、特定することは不可能であるということに注意が必要である。ある主体（例、企業）が選択肢B（プロモーションしない）ではなく、A（プロモーションする）を選ぶことの因果効果は、その人がある選択肢Aを選び、成果（売上）を確認した後、時間を戻し選択肢Bを選んだ場合の成果を改めて確認することで初めて確認することができる。

しかし、そのような方法は現実的ではないので、実際には「平均的な効果としての因果関係」をあの手この手を使って追求していくことになる。また、もし 2 つの変数間に因果関係がある場合、その影響の程度を「因果効果」と呼ぶ。このようにして平均的な因果関係を識別することを目的とした分析アプローチは因果推論と呼ばれ、近年多くのマーケティング研究に応用されている。

因果推論は経済学や公衆衛生の領域を中心に手法が発展、応用されており、日本においては一般向けの書籍から研究者向けの専門書まで幅広く出版されている。因果推論に関する詳細な説明はこれらの図書に譲るものの、近年の因果推論の重要性はマーケティング領域としても無視できない。そのため、以降のコラムを通じて因果推論における主要な方法とそのマーケティング研究への応用例を紹介していく。具体的には、ランダム化比較試験、操作変数法、差の差の分析法について紹介する。なお、因果推論のアプローチとしては、回帰不連続法や、マッチング法、傾向スコアを用いた手法も多く活用されている。本書では紙幅の都合上これらの方法について言及しないので、関心のある方は川口・澤田（2024）や西山ほか（2019）を参照してほしい。

## 参考文献
川口康平・澤田真行 (2024)「因果推論の計量経済学」，日本評論社.

立森久照（2016）「因果推論ことはじめ」『岩波データサイエンス vol.3』, 7-27.

西山慶彦・新谷元嗣・川口大司・奥井亮（2019）「計量経済学」，有斐閣.

中村牧子・津川友介（2017）『「原因と結果」の経済学 データから真実を見抜く思考法』,ダイヤモンド社.