<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.5 重回帰モデル | マーケティングリサーチの進め方</title>
  <meta name="description" content="7.5 重回帰モデル | マーケティングリサーチの進め方" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="7.5 重回帰モデル | マーケティングリサーチの進め方" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="https://github.com/tak-tag/MktRes_Lecture.git" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.5 重回帰モデル | マーケティングリサーチの進め方" />
  
  
  



<meta name="date" content="2025-04-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="回帰分析における推定と検定.html"/>
<link rel="next" href="練習問題-3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Marketing Research Lecture Note</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> はじめに（本書について）</a></li>
<li class="chapter" data-level="2" data-path="rusage.html"><a href="rusage.html"><i class="fa fa-check"></i><b>2</b> R と R studioに慣れる</a>
<ul>
<li class="chapter" data-level="2.1" data-path="desktop.html"><a href="desktop.html"><i class="fa fa-check"></i><b>2.1</b> R studio デスクトップ版の利用</a></li>
<li class="chapter" data-level="2.2" data-path="プロジェクト機能について.html"><a href="プロジェクト機能について.html"><i class="fa fa-check"></i><b>2.2</b> プロジェクト機能について</a></li>
<li class="chapter" data-level="2.3" data-path="rの基本操作.html"><a href="rの基本操作.html"><i class="fa fa-check"></i><b>2.3</b> Rの基本操作</a></li>
<li class="chapter" data-level="2.4" data-path="r-スクリプトのすゝめ.html"><a href="r-スクリプトのすゝめ.html"><i class="fa fa-check"></i><b>2.4</b> R スクリプトのすゝめ</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="r-スクリプトのすゝめ.html"><a href="r-スクリプトのすゝめ.html#rスクリプトを書く"><i class="fa fa-check"></i><b>2.4.1</b> Rスクリプトを書く</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="本章のまとめ.html"><a href="本章のまとめ.html"><i class="fa fa-check"></i><b>2.5</b> 本章のまとめ</a></li>
<li class="chapter" data-level="2.6" data-path="コラムposit-cloudを使ってみる.html"><a href="コラムposit-cloudを使ってみる.html"><i class="fa fa-check"></i><b>2.6</b> コラム：Posit cloudを使ってみる</a></li>
<li class="chapter" data-level="2.7" data-path="参考文献.html"><a href="参考文献.html"><i class="fa fa-check"></i><b>2.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="design.html"><a href="design.html"><i class="fa fa-check"></i><b>3</b> リサーチデザインと問いの設定</a>
<ul>
<li class="chapter" data-level="3.1" data-path="本章の概要.html"><a href="本章の概要.html"><i class="fa fa-check"></i><b>3.1</b> 本章の概要</a></li>
<li class="chapter" data-level="3.2" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html"><i class="fa fa-check"></i><b>3.2</b> マーケティング実務とリサーチ</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#実務とリサーチの異なる視点"><i class="fa fa-check"></i><b>3.2.1</b> 実務とリサーチの異なる視点</a></li>
<li class="chapter" data-level="3.2.2" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#マーケティングリサーチと実務的含意"><i class="fa fa-check"></i><b>3.2.2</b> マーケティングリサーチと実務的含意</a></li>
<li class="chapter" data-level="3.2.3" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#非計画購買に関する研究紹介"><i class="fa fa-check"></i><b>3.2.3</b> 非計画購買に関する研究紹介</a></li>
<li class="chapter" data-level="3.2.4" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#マネジメントとリサーチの分離"><i class="fa fa-check"></i><b>3.2.4</b> マネジメントとリサーチの分離</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="リサーチデザインとアプローチの類型.html"><a href="リサーチデザインとアプローチの類型.html"><i class="fa fa-check"></i><b>3.3</b> リサーチデザインとアプローチの類型</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="リサーチデザインとアプローチの類型.html"><a href="リサーチデザインとアプローチの類型.html#異なる研究アプローチ理論重視と観察重視アプローチ"><i class="fa fa-check"></i><b>3.3.1</b> 異なる研究アプローチ（理論重視と観察重視アプローチ）</a></li>
<li class="chapter" data-level="3.3.2" data-path="リサーチデザインとアプローチの類型.html"><a href="リサーチデザインとアプローチの類型.html#理論重視研究と論文の構成"><i class="fa fa-check"></i><b>3.3.2</b> 理論重視研究と論文の構成</a></li>
<li class="chapter" data-level="3.3.3" data-path="リサーチデザインとアプローチの類型.html"><a href="リサーチデザインとアプローチの類型.html#企業リサーチにおけるレポート"><i class="fa fa-check"></i><b>3.3.3</b> 企業リサーチにおけるレポート</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="question.html"><a href="question.html"><i class="fa fa-check"></i><b>3.4</b> 研究課題（問い）の設定</a></li>
<li class="chapter" data-level="3.5" data-path="問題と分析をつなげる仮説の提示.html"><a href="問題と分析をつなげる仮説の提示.html"><i class="fa fa-check"></i><b>3.5</b> 問題と分析をつなげる仮説の提示</a></li>
<li class="chapter" data-level="3.6" data-path="philophy.html"><a href="philophy.html"><i class="fa fa-check"></i><b>3.6</b> 学術的研究のための留意点</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="philophy.html"><a href="philophy.html#マーケティング研究と科学哲学"><i class="fa fa-check"></i><b>3.6.1</b> マーケティング研究と科学哲学</a></li>
<li class="chapter" data-level="3.6.2" data-path="philophy.html"><a href="philophy.html#elaboration"><i class="fa fa-check"></i><b>3.6.2</b> 研究における理論の利用と精緻化</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="研究課題と仮説の設定例.html"><a href="研究課題と仮説の設定例.html"><i class="fa fa-check"></i><b>3.7</b> 研究課題と仮説の設定例</a></li>
<li class="chapter" data-level="3.8" data-path="練習問題.html"><a href="練習問題.html"><i class="fa fa-check"></i><b>3.8</b> 練習問題</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="練習問題.html"><a href="練習問題.html#研究課題の導出"><i class="fa fa-check"></i><b>3.8.1</b> 研究課題の導出</a></li>
<li class="chapter" data-level="3.8.2" data-path="練習問題.html"><a href="練習問題.html#仮説の導出"><i class="fa fa-check"></i><b>3.8.2</b> 仮説の導出</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="参考文献-1.html"><a href="参考文献-1.html"><i class="fa fa-check"></i><b>3.9</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="survey.html"><a href="survey.html"><i class="fa fa-check"></i><b>4</b> 尺度と質問紙調査設計</a>
<ul>
<li class="chapter" data-level="4.1" data-path="本章の概要-1.html"><a href="本章の概要-1.html"><i class="fa fa-check"></i><b>4.1</b> 本章の概要</a></li>
<li class="chapter" data-level="4.2" data-path="psychscale.html"><a href="psychscale.html"><i class="fa fa-check"></i><b>4.2</b> マーケティングリサーチにおける質問紙調査の活用</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="psychscale.html"><a href="psychscale.html#データのタイプ"><i class="fa fa-check"></i><b>4.2.1</b> データのタイプ</a></li>
<li class="chapter" data-level="4.2.2" data-path="psychscale.html"><a href="psychscale.html#質問紙調査とは"><i class="fa fa-check"></i><b>4.2.2</b> 質問紙調査とは</a></li>
<li class="chapter" data-level="4.2.3" data-path="psychscale.html"><a href="psychscale.html#マーケティングと質問紙調査"><i class="fa fa-check"></i><b>4.2.3</b> マーケティングと質問紙調査</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>4.3</b> 調査対象者の確保</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="sampling.html"><a href="sampling.html#サンプリング手法"><i class="fa fa-check"></i><b>4.3.1</b> サンプリング手法</a></li>
<li class="chapter" data-level="4.3.2" data-path="sampling.html"><a href="sampling.html#サンプルサイズの決定"><i class="fa fa-check"></i><b>4.3.2</b> サンプルサイズの決定</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="尺度の種類と質問項目.html"><a href="尺度の種類と質問項目.html"><i class="fa fa-check"></i><b>4.4</b> 尺度の種類と質問項目</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="尺度の種類と質問項目.html"><a href="尺度の種類と質問項目.html#measurement"><i class="fa fa-check"></i><b>4.4.1</b> 心理尺度</a></li>
<li class="chapter" data-level="4.4.2" data-path="尺度の種類と質問項目.html"><a href="尺度の種類と質問項目.html#質問項目と解答欄"><i class="fa fa-check"></i><b>4.4.2</b> 質問項目と解答欄</a></li>
<li class="chapter" data-level="4.4.3" data-path="尺度の種類と質問項目.html"><a href="尺度の種類と質問項目.html#マーケティングと心理尺度"><i class="fa fa-check"></i><b>4.4.3</b> マーケティングと心理尺度</a></li>
<li class="chapter" data-level="4.4.4" data-path="尺度の種類と質問項目.html"><a href="尺度の種類と質問項目.html#信頼性と妥当性"><i class="fa fa-check"></i><b>4.4.4</b> 信頼性と妥当性</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="実践的な注意点.html"><a href="実践的な注意点.html"><i class="fa fa-check"></i><b>4.5</b> 実践的な注意点</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="実践的な注意点.html"><a href="実践的な注意点.html#wording"><i class="fa fa-check"></i><b>4.5.1</b> 質問におけるワーディング</a></li>
<li class="chapter" data-level="4.5.2" data-path="実践的な注意点.html"><a href="実践的な注意点.html#surveystructure"><i class="fa fa-check"></i><b>4.5.2</b> 質問票の構成</a></li>
<li class="chapter" data-level="4.5.3" data-path="実践的な注意点.html"><a href="実践的な注意点.html#調査回答の質向上にむけた工夫"><i class="fa fa-check"></i><b>4.5.3</b> 調査回答の質向上にむけた工夫</a></li>
<li class="chapter" data-level="4.5.4" data-path="実践的な注意点.html"><a href="実践的な注意点.html#変数間の関係を捉えるための質問紙調査設計"><i class="fa fa-check"></i><b>4.5.4</b> 変数間の関係を捉えるための質問紙調査設計</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ethicality.html"><a href="ethicality.html"><i class="fa fa-check"></i><b>4.6</b> 研究倫理について</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="ethicality.html"><a href="ethicality.html#質問紙調査ととインフォームドコンセント"><i class="fa fa-check"></i><b>4.6.1</b> 質問紙調査ととインフォームド・コンセント</a></li>
<li class="chapter" data-level="4.6.2" data-path="ethicality.html"><a href="ethicality.html#研究倫理と事前登録"><i class="fa fa-check"></i><b>4.6.2</b> 研究倫理と事前登録</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="練習問題-1.html"><a href="練習問題-1.html"><i class="fa fa-check"></i><b>4.7</b> 練習問題</a></li>
<li class="chapter" data-level="4.8" data-path="参考文献-2.html"><a href="参考文献-2.html"><i class="fa fa-check"></i><b>4.8</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="handling.html"><a href="handling.html"><i class="fa fa-check"></i><b>5</b> データ整理と要約・可視化</a>
<ul>
<li class="chapter" data-level="5.1" data-path="本章の概要-2.html"><a href="本章の概要-2.html"><i class="fa fa-check"></i><b>5.1</b> 本章の概要</a></li>
<li class="chapter" data-level="5.2" data-path="データの読み込み.html"><a href="データの読み込み.html"><i class="fa fa-check"></i><b>5.2</b> データの読み込み</a></li>
<li class="chapter" data-level="5.3" data-path="データの整形.html"><a href="データの整形.html"><i class="fa fa-check"></i><b>5.3</b> データの整形</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="データの整形.html"><a href="データの整形.html#tidyverse-の活用"><i class="fa fa-check"></i><b>5.3.1</b> tidyverse の活用</a></li>
<li class="chapter" data-level="5.3.2" data-path="データの整形.html"><a href="データの整形.html#企業データの処理"><i class="fa fa-check"></i><b>5.3.2</b> 企業データの処理</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="データの要約と可視化.html"><a href="データの要約と可視化.html"><i class="fa fa-check"></i><b>5.4</b> データの要約と可視化</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="データの要約と可視化.html"><a href="データの要約と可視化.html#記述統計"><i class="fa fa-check"></i><b>5.4.1</b> 記述統計</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="カテゴリ変数の要約.html"><a href="カテゴリ変数の要約.html"><i class="fa fa-check"></i><b>5.5</b> カテゴリ変数の要約</a></li>
<li class="chapter" data-level="5.6" data-path="データの可視化.html"><a href="データの可視化.html"><i class="fa fa-check"></i><b>5.6</b> データの可視化</a></li>
<li class="chapter" data-level="5.7" data-path="二変数間の関係の要約.html"><a href="二変数間の関係の要約.html"><i class="fa fa-check"></i><b>5.7</b> 二変数間の関係の要約</a></li>
<li class="chapter" data-level="5.8" data-path="statex.html"><a href="statex.html"><i class="fa fa-check"></i><b>5.8</b> 練習問題</a></li>
<li class="chapter" data-level="5.9" data-path="参考文献-3.html"><a href="参考文献-3.html"><i class="fa fa-check"></i><b>5.9</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="test.html"><a href="test.html"><i class="fa fa-check"></i><b>6</b> 基礎統計学復習</a>
<ul>
<li class="chapter" data-level="6.1" data-path="本章の概要-3.html"><a href="本章の概要-3.html"><i class="fa fa-check"></i><b>6.1</b> 本章の概要</a></li>
<li class="chapter" data-level="6.2" data-path="確率モデル期待値と分散.html"><a href="確率モデル期待値と分散.html"><i class="fa fa-check"></i><b>6.2</b> 確率モデル、期待値と分散</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="確率モデル期待値と分散.html"><a href="確率モデル期待値と分散.html#確率と離散確率変数"><i class="fa fa-check"></i><b>6.2.1</b> 確率と離散確率変数</a></li>
<li class="chapter" data-level="6.2.2" data-path="確率モデル期待値と分散.html"><a href="確率モデル期待値と分散.html#連続確率変数"><i class="fa fa-check"></i><b>6.2.2</b> 連続確率変数</a></li>
<li class="chapter" data-level="6.2.3" data-path="確率モデル期待値と分散.html"><a href="確率モデル期待値と分散.html#期待値"><i class="fa fa-check"></i><b>6.2.3</b> 期待値</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="統計的推測.html"><a href="統計的推測.html"><i class="fa fa-check"></i><b>6.3</b> 統計的推測</a></li>
<li class="chapter" data-level="6.4" data-path="pestimate.html"><a href="pestimate.html"><i class="fa fa-check"></i><b>6.4</b> 点推定</a></li>
<li class="chapter" data-level="6.5" data-path="推定量もまた確率変数.html"><a href="推定量もまた確率変数.html"><i class="fa fa-check"></i><b>6.5</b> 推定量もまた確率変数</a></li>
<li class="chapter" data-level="6.6" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html"><i class="fa fa-check"></i><b>6.6</b> 補足（いくつかの確率分布の関係性）</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#正規分布"><i class="fa fa-check"></i><b>6.6.1</b> 正規分布</a></li>
<li class="chapter" data-level="6.6.2" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#カイ二乗分布"><i class="fa fa-check"></i><b>6.6.2</b> カイ二乗分布</a></li>
<li class="chapter" data-level="6.6.3" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#t分布"><i class="fa fa-check"></i><b>6.6.3</b> t分布</a></li>
<li class="chapter" data-level="6.6.4" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#f分布"><i class="fa fa-check"></i><b>6.6.4</b> F分布</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="intinf.html"><a href="intinf.html"><i class="fa fa-check"></i><b>6.7</b> 区間推定</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="intinf.html"><a href="intinf.html#標準正規分布に基づく信頼区間の求め方"><i class="fa fa-check"></i><b>6.7.1</b> 標準正規分布に基づく信頼区間の求め方*</a></li>
<li class="chapter" data-level="6.7.2" data-path="intinf.html"><a href="intinf.html#t分布を使った区間推定"><i class="fa fa-check"></i><b>6.7.2</b> t分布を使った区間推定*</a></li>
<li class="chapter" data-level="6.7.3" data-path="intinf.html"><a href="intinf.html#rによる区間推定"><i class="fa fa-check"></i><b>6.7.3</b> Rによる区間推定</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html"><i class="fa fa-check"></i><b>6.8</b> 統計的仮説検定</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#nullhypo"><i class="fa fa-check"></i><b>6.8.1</b> 検定の手順と仮説</a></li>
<li class="chapter" data-level="6.8.2" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#母平均の検定両側検定に関する理屈"><i class="fa fa-check"></i><b>6.8.2</b> 母平均の検定（両側検定）に関する理屈</a></li>
<li class="chapter" data-level="6.8.3" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#片側検定の紹介"><i class="fa fa-check"></i><b>6.8.3</b> 片側検定の紹介</a></li>
<li class="chapter" data-level="6.8.4" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#有意水準と検定における誤り"><i class="fa fa-check"></i><b>6.8.4</b> 有意水準と検定における誤り</a></li>
<li class="chapter" data-level="6.8.5" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#検定結果に関する解釈"><i class="fa fa-check"></i><b>6.8.5</b> 検定結果に関する解釈</a></li>
<li class="chapter" data-level="6.8.6" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html#電球データと検定"><i class="fa fa-check"></i><b>6.8.6</b> 電球データと検定</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="平均値に関するその他の検定.html"><a href="平均値に関するその他の検定.html"><i class="fa fa-check"></i><b>6.9</b> 平均値に関するその他の検定</a></li>
<li class="chapter" data-level="6.10" data-path="分散分析.html"><a href="分散分析.html"><i class="fa fa-check"></i><b>6.10</b> 分散分析</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="分散分析.html"><a href="分散分析.html#分散分析についてのモデル表現"><i class="fa fa-check"></i><b>6.10.1</b> 分散分析についてのモデル表現*</a></li>
<li class="chapter" data-level="6.10.2" data-path="分散分析.html"><a href="分散分析.html#二元配置分散分析"><i class="fa fa-check"></i><b>6.10.2</b> 二元配置分散分析*</a></li>
<li class="chapter" data-level="6.10.3" data-path="分散分析.html"><a href="分散分析.html#二元配置モデルの効果検定"><i class="fa fa-check"></i><b>6.10.3</b> 二元配置モデルの効果検定*</a></li>
<li class="chapter" data-level="6.10.4" data-path="分散分析.html"><a href="分散分析.html#tukey"><i class="fa fa-check"></i><b>6.10.4</b> 多重比較とそれに伴う統計的問題</a></li>
<li class="chapter" data-level="6.10.5" data-path="分散分析.html"><a href="分散分析.html#rによる分散分析の実行"><i class="fa fa-check"></i><b>6.10.5</b> Rによる分散分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="pwr.html"><a href="pwr.html"><i class="fa fa-check"></i><b>6.11</b> 検定力分析とサンプルサイズ</a></li>
<li class="chapter" data-level="6.12" data-path="練習問題-2.html"><a href="練習問題-2.html"><i class="fa fa-check"></i><b>6.12</b> 練習問題</a>
<ul>
<li class="chapter" data-level="6.12.1" data-path="練習問題-2.html"><a href="練習問題-2.html#仮説検定の理屈"><i class="fa fa-check"></i><b>6.12.1</b> 仮説検定の理屈</a></li>
<li class="chapter" data-level="6.12.2" data-path="練習問題-2.html"><a href="練習問題-2.html#仮説検定の解釈"><i class="fa fa-check"></i><b>6.12.2</b> 仮説検定の解釈</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="参考文献-4.html"><a href="参考文献-4.html"><i class="fa fa-check"></i><b>6.13</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regintro.html"><a href="regintro.html"><i class="fa fa-check"></i><b>7</b> 回帰分析</a>
<ul>
<li class="chapter" data-level="7.1" data-path="本章の概要-4.html"><a href="本章の概要-4.html"><i class="fa fa-check"></i><b>7.1</b> 本章の概要</a></li>
<li class="chapter" data-level="7.2" data-path="分析準備.html"><a href="分析準備.html"><i class="fa fa-check"></i><b>7.2</b> 分析準備</a></li>
<li class="chapter" data-level="7.3" data-path="単回帰モデルと予測値.html"><a href="単回帰モデルと予測値.html"><i class="fa fa-check"></i><b>7.3</b> 単回帰モデルと予測値</a></li>
<li class="chapter" data-level="7.4" data-path="回帰分析における推定と検定.html"><a href="回帰分析における推定と検定.html"><i class="fa fa-check"></i><b>7.4</b> 回帰分析における推定と検定</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="回帰分析における推定と検定.html"><a href="回帰分析における推定と検定.html#企業データを用いた回帰分析の実行"><i class="fa fa-check"></i><b>7.4.1</b> 企業データを用いた回帰分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="重回帰モデル.html"><a href="重回帰モデル.html"><i class="fa fa-check"></i><b>7.5</b> 重回帰モデル</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="重回帰モデル.html"><a href="重回帰モデル.html#重回帰モデル概要"><i class="fa fa-check"></i><b>7.5.1</b> 重回帰モデル概要</a></li>
<li class="chapter" data-level="7.5.2" data-path="重回帰モデル.html"><a href="重回帰モデル.html#重回帰モデルの記述と性質"><i class="fa fa-check"></i><b>7.5.2</b> 重回帰モデルの記述と性質</a></li>
<li class="chapter" data-level="7.5.3" data-path="重回帰モデル.html"><a href="重回帰モデル.html#重回帰分析におけるモデル適合度"><i class="fa fa-check"></i><b>7.5.3</b> 重回帰分析におけるモデル適合度</a></li>
<li class="chapter" data-level="7.5.4" data-path="重回帰モデル.html"><a href="重回帰モデル.html#回帰係数の解釈"><i class="fa fa-check"></i><b>7.5.4</b> 回帰係数の解釈</a></li>
<li class="chapter" data-level="7.5.5" data-path="重回帰モデル.html"><a href="重回帰モデル.html#単回帰モデルと重回帰モデルの比較"><i class="fa fa-check"></i><b>7.5.5</b> 単回帰モデルと重回帰モデルの比較</a></li>
<li class="chapter" data-level="7.5.6" data-path="重回帰モデル.html"><a href="重回帰モデル.html#varsel"><i class="fa fa-check"></i><b>7.5.6</b> 重回帰モデルにおける変数選択</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="練習問題-3.html"><a href="練習問題-3.html"><i class="fa fa-check"></i><b>7.6</b> 練習問題</a></li>
<li class="chapter" data-level="7.7" data-path="参考文献-5.html"><a href="参考文献-5.html"><i class="fa fa-check"></i><b>7.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regtechnic.html"><a href="regtechnic.html"><i class="fa fa-check"></i><b>8</b> 回帰分析上の工夫紹介</a>
<ul>
<li class="chapter" data-level="8.1" data-path="本章の概要-5.html"><a href="本章の概要-5.html"><i class="fa fa-check"></i><b>8.1</b> 本章の概要</a></li>
<li class="chapter" data-level="8.2" data-path="dummy.html"><a href="dummy.html"><i class="fa fa-check"></i><b>8.2</b> ダミー変数</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="dummy.html"><a href="dummy.html#企業データを用いた分析の実行"><i class="fa fa-check"></i><b>8.2.1</b> 企業データを用いた分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="交差項.html"><a href="交差項.html"><i class="fa fa-check"></i><b>8.3</b> 交差項</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="交差項.html"><a href="交差項.html#傾きダミー"><i class="fa fa-check"></i><b>8.3.1</b> 傾きダミー</a></li>
<li class="chapter" data-level="8.3.2" data-path="交差項.html"><a href="交差項.html#傾きダミーの実行"><i class="fa fa-check"></i><b>8.3.2</b> 傾きダミーの実行</a></li>
<li class="chapter" data-level="8.3.3" data-path="交差項.html"><a href="交差項.html#量的変数同士の交差項"><i class="fa fa-check"></i><b>8.3.3</b> 量的変数同士の交差項</a></li>
<li class="chapter" data-level="8.3.4" data-path="交差項.html"><a href="交差項.html#交差項モデルの実行"><i class="fa fa-check"></i><b>8.3.4</b> 交差項モデルの実行</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="係数比較.html"><a href="係数比較.html"><i class="fa fa-check"></i><b>8.4</b> 係数比較</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="係数比較.html"><a href="係数比較.html#係数比較の実行"><i class="fa fa-check"></i><b>8.4.1</b> 係数比較の実行</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="対数線形.html"><a href="対数線形.html"><i class="fa fa-check"></i><b>8.5</b> 対数線形</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="対数線形.html"><a href="対数線形.html#対数線形モデルの分析実行"><i class="fa fa-check"></i><b>8.5.1</b> 対数線形モデルの分析実行</a></li>
<li class="chapter" data-level="8.5.2" data-path="対数線形.html"><a href="対数線形.html#需要の価格弾力性について"><i class="fa fa-check"></i><b>8.5.2</b> 需要の価格弾力性について*</a></li>
<li class="chapter" data-level="8.5.3" data-path="対数線形.html"><a href="対数線形.html#対数線形の推定と検定"><i class="fa fa-check"></i><b>8.5.3</b> 対数線形の推定と検定</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="練習問題-4.html"><a href="練習問題-4.html"><i class="fa fa-check"></i><b>8.6</b> 練習問題</a></li>
<li class="chapter" data-level="8.7" data-path="参考文献-6.html"><a href="参考文献-6.html"><i class="fa fa-check"></i><b>8.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="choice.html"><a href="choice.html"><i class="fa fa-check"></i><b>9</b> 消費者の選択と離散選択モデル</a>
<ul>
<li class="chapter" data-level="9.1" data-path="本章の概要-6.html"><a href="本章の概要-6.html"><i class="fa fa-check"></i><b>9.1</b> 本章の概要</a></li>
<li class="chapter" data-level="9.2" data-path="rational.html"><a href="rational.html"><i class="fa fa-check"></i><b>9.2</b> 消費者選択と合理的消費者像概観</a></li>
<li class="chapter" data-level="9.3" data-path="utility.html"><a href="utility.html"><i class="fa fa-check"></i><b>9.3</b> 選択行動と効用最大化</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="utility.html"><a href="utility.html#step-1-どのような消費者を考察の対象にするのか"><i class="fa fa-check"></i><b>9.3.1</b> Step 1: どのような消費者を考察の対象にするのか</a></li>
<li class="chapter" data-level="9.3.2" data-path="utility.html"><a href="utility.html#step-2-選好モデルと効用"><i class="fa fa-check"></i><b>9.3.2</b> Step 2: 選好モデルと効用</a></li>
<li class="chapter" data-level="9.3.3" data-path="utility.html"><a href="utility.html#step-3-効用最大化"><i class="fa fa-check"></i><b>9.3.3</b> Step 3: 効用最大化</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="discrete.html"><a href="discrete.html"><i class="fa fa-check"></i><b>9.4</b> 離散選択モデル</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="discrete.html"><a href="discrete.html#線形確率モデル"><i class="fa fa-check"></i><b>9.4.1</b> 線形確率モデル</a></li>
<li class="chapter" data-level="9.4.2" data-path="discrete.html"><a href="discrete.html#プロビットモデルとロジットモデル"><i class="fa fa-check"></i><b>9.4.2</b> プロビットモデルとロジットモデル*</a></li>
<li class="chapter" data-level="9.4.3" data-path="discrete.html"><a href="discrete.html#潜在変数アプローチによる説明"><i class="fa fa-check"></i><b>9.4.3</b> 潜在変数アプローチによる説明*</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="プロビットモデルの推定と解釈.html"><a href="プロビットモデルの推定と解釈.html"><i class="fa fa-check"></i><b>9.5</b> プロビットモデルの推定と解釈</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="プロビットモデルの推定と解釈.html"><a href="プロビットモデルの推定と解釈.html#分析の実行と結果のまとめ"><i class="fa fa-check"></i><b>9.5.1</b> 分析の実行と結果のまとめ</a></li>
<li class="chapter" data-level="9.5.2" data-path="プロビットモデルの推定と解釈.html"><a href="プロビットモデルの推定と解釈.html#限界効果の計算"><i class="fa fa-check"></i><b>9.5.2</b> 限界効果の計算</a></li>
<li class="chapter" data-level="9.5.3" data-path="プロビットモデルの推定と解釈.html"><a href="プロビットモデルの推定と解釈.html#限界効果がなぜ必要か"><i class="fa fa-check"></i><b>9.5.3</b> 限界効果がなぜ必要か？*</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="ml.html"><a href="ml.html"><i class="fa fa-check"></i><b>9.6</b> 補足：最尤推定法の紹介</a></li>
<li class="chapter" data-level="9.7" data-path="離散選択モデルへの合理的消費者像の応用.html"><a href="離散選択モデルへの合理的消費者像の応用.html"><i class="fa fa-check"></i><b>9.7</b> 離散選択モデルへの合理的消費者像の応用</a></li>
<li class="chapter" data-level="9.8" data-path="多項選択モデル紹介.html"><a href="多項選択モデル紹介.html"><i class="fa fa-check"></i><b>9.8</b> 多項選択モデル紹介</a></li>
<li class="chapter" data-level="9.9" data-path="需要の予測と本章のまとめ.html"><a href="需要の予測と本章のまとめ.html"><i class="fa fa-check"></i><b>9.9</b> 需要の予測と本章のまとめ</a></li>
<li class="chapter" data-level="9.10" data-path="参考文献-7.html"><a href="参考文献-7.html"><i class="fa fa-check"></i><b>9.10</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="empirics.html"><a href="empirics.html"><i class="fa fa-check"></i><b>10</b> 観察重視アプローチ</a>
<ul>
<li class="chapter" data-level="10.1" data-path="本章の概要-7.html"><a href="本章の概要-7.html"><i class="fa fa-check"></i><b>10.1</b> 本章の概要</a></li>
<li class="chapter" data-level="10.2" data-path="観察重視アプローチ.html"><a href="観察重視アプローチ.html"><i class="fa fa-check"></i><b>10.2</b> 観察重視アプローチ</a></li>
<li class="chapter" data-level="10.3" data-path="観察重視アプローチの研究プロセス.html"><a href="観察重視アプローチの研究プロセス.html"><i class="fa fa-check"></i><b>10.3</b> 観察重視アプローチの研究プロセス</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="観察重視アプローチの研究プロセス.html"><a href="観察重視アプローチの研究プロセス.html#研究機会の特定"><i class="fa fa-check"></i><b>10.3.1</b> 研究機会の特定</a></li>
<li class="chapter" data-level="10.3.2" data-path="観察重視アプローチの研究プロセス.html"><a href="観察重視アプローチの研究プロセス.html#地形探索"><i class="fa fa-check"></i><b>10.3.2</b> 地形探索</a></li>
<li class="chapter" data-level="10.3.3" data-path="観察重視アプローチの研究プロセス.html"><a href="観察重視アプローチの研究プロセス.html#理解の発展"><i class="fa fa-check"></i><b>10.3.3</b> 理解の発展</a></li>
<li class="chapter" data-level="10.3.4" data-path="観察重視アプローチの研究プロセス.html"><a href="観察重視アプローチの研究プロセス.html#efアプローチ研究の報告"><i class="fa fa-check"></i><b>10.3.4</b> EFアプローチ研究の報告</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="efアプローチ研究例.html"><a href="efアプローチ研究例.html"><i class="fa fa-check"></i><b>10.4</b> EFアプローチ研究例</a></li>
<li class="chapter" data-level="10.5" data-path="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html"><a href="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html"><i class="fa fa-check"></i><b>10.5</b> 簡易的なデータ探索法紹介：統計的分析を用いない顧客分析</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html"><a href="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html#crm"><i class="fa fa-check"></i><b>10.5.1</b> データ処理と顧客関係管理（CRM）</a></li>
<li class="chapter" data-level="10.5.2" data-path="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html"><a href="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html#データの構造変化とソート"><i class="fa fa-check"></i><b>10.5.2</b> データの構造変化とソート</a></li>
<li class="chapter" data-level="10.5.3" data-path="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html"><a href="簡易的なデータ探索法紹介統計的分析を用いない顧客分析.html#データ結合"><i class="fa fa-check"></i><b>10.5.3</b> データ結合</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="練習問題-5.html"><a href="練習問題-5.html"><i class="fa fa-check"></i><b>10.6</b> 練習問題</a></li>
<li class="chapter" data-level="10.7" data-path="参考文献-8.html"><a href="参考文献-8.html"><i class="fa fa-check"></i><b>10.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="cluster.html"><a href="cluster.html"><i class="fa fa-check"></i><b>11</b> セグメントとクラスター分析</a>
<ul>
<li class="chapter" data-level="11.1" data-path="本章の概要-8.html"><a href="本章の概要-8.html"><i class="fa fa-check"></i><b>11.1</b> 本章の概要</a></li>
<li class="chapter" data-level="11.2" data-path="セグメンテーションとマーケティング意思決定.html"><a href="セグメンテーションとマーケティング意思決定.html"><i class="fa fa-check"></i><b>11.2</b> セグメンテーションとマーケティング意思決定</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="セグメンテーションとマーケティング意思決定.html"><a href="セグメンテーションとマーケティング意思決定.html#stpその後"><i class="fa fa-check"></i><b>11.2.1</b> STPその後</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="セグメンテーションの実行とクラスター分析.html"><a href="セグメンテーションの実行とクラスター分析.html"><i class="fa fa-check"></i><b>11.3</b> セグメンテーションの実行とクラスター分析</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="セグメンテーションの実行とクラスター分析.html"><a href="セグメンテーションの実行とクラスター分析.html#Hier"><i class="fa fa-check"></i><b>11.3.1</b> 階層的クラスター分析</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="k-means.html"><a href="k-means.html"><i class="fa fa-check"></i><b>11.4</b> 非階層的クラスター分析：K-means法</a></li>
<li class="chapter" data-level="11.5" data-path="rによるクラスター分析の実行.html"><a href="rによるクラスター分析の実行.html"><i class="fa fa-check"></i><b>11.5</b> Rによるクラスター分析の実行</a></li>
<li class="chapter" data-level="11.6" data-path="練習問題-6.html"><a href="練習問題-6.html"><i class="fa fa-check"></i><b>11.6</b> 練習問題</a></li>
<li class="chapter" data-level="11.7" data-path="参考文献-9.html"><a href="参考文献-9.html"><i class="fa fa-check"></i><b>11.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="factor.html"><a href="factor.html"><i class="fa fa-check"></i><b>12</b> 探索的因子分析と知覚マップ</a>
<ul>
<li class="chapter" data-level="12.1" data-path="本章の概要-9.html"><a href="本章の概要-9.html"><i class="fa fa-check"></i><b>12.1</b> 本章の概要</a></li>
<li class="chapter" data-level="12.2" data-path="因子分析とは.html"><a href="因子分析とは.html"><i class="fa fa-check"></i><b>12.2</b> 因子分析とは</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="因子分析とは.html"><a href="因子分析とは.html#因子分析の概要とモデルの構造"><i class="fa fa-check"></i><b>12.2.1</b> 因子分析の概要とモデルの構造</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="因子モデル.html"><a href="因子モデル.html"><i class="fa fa-check"></i><b>12.3</b> 2因子モデル</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="因子モデル.html"><a href="因子モデル.html#因子軸の回転"><i class="fa fa-check"></i><b>12.3.1</b> 因子軸の回転</a></li>
<li class="chapter" data-level="12.3.2" data-path="因子モデル.html"><a href="因子モデル.html#因子数の決定"><i class="fa fa-check"></i><b>12.3.2</b> 因子数の決定</a></li>
<li class="chapter" data-level="12.3.3" data-path="因子モデル.html"><a href="因子モデル.html#得点化"><i class="fa fa-check"></i><b>12.3.3</b> 得点化</a></li>
<li class="chapter" data-level="12.3.4" data-path="因子モデル.html"><a href="因子モデル.html#因子モデルまとめ"><i class="fa fa-check"></i><b>12.3.4</b> 2因子モデルまとめ</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="ポジショニングと知覚マップ概要.html"><a href="ポジショニングと知覚マップ概要.html"><i class="fa fa-check"></i><b>12.4</b> ポジショニングと知覚マップ概要</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ポジショニングと知覚マップ概要.html"><a href="ポジショニングと知覚マップ概要.html#ポジショニングについて"><i class="fa fa-check"></i><b>12.4.1</b> ポジショニングについて</a></li>
<li class="chapter" data-level="12.4.2" data-path="ポジショニングと知覚マップ概要.html"><a href="ポジショニングと知覚マップ概要.html#知覚マップ"><i class="fa fa-check"></i><b>12.4.2</b> 知覚マップ</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="faex.html"><a href="faex.html"><i class="fa fa-check"></i><b>12.5</b> Rによる因子分析の実行</a></li>
<li class="chapter" data-level="12.6" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html"><i class="fa fa-check"></i><b>12.6</b> アンケートデータと知覚マップ</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html#データ構造の変更"><i class="fa fa-check"></i><b>12.6.1</b> データ構造の変更</a></li>
<li class="chapter" data-level="12.6.2" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html#因子分析の実行"><i class="fa fa-check"></i><b>12.6.2</b> 因子分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="練習問題-7.html"><a href="練習問題-7.html"><i class="fa fa-check"></i><b>12.7</b> 練習問題</a></li>
<li class="chapter" data-level="12.8" data-path="参考文献-10.html"><a href="参考文献-10.html"><i class="fa fa-check"></i><b>12.8</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="psm.html"><a href="psm.html"><i class="fa fa-check"></i><b>13</b> 価格感度測定 (PSM)</a>
<ul>
<li class="chapter" data-level="13.1" data-path="本章の概要-10.html"><a href="本章の概要-10.html"><i class="fa fa-check"></i><b>13.1</b> 本章の概要</a></li>
<li class="chapter" data-level="13.2" data-path="psmrunning.html"><a href="psmrunning.html"><i class="fa fa-check"></i><b>13.2</b> PSMの実行と結果</a></li>
<li class="chapter" data-level="13.3" data-path="price_concept.html"><a href="price_concept.html"><i class="fa fa-check"></i><b>13.3</b> マーケティングにおける価格概念</a></li>
<li class="chapter" data-level="13.4" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html"><i class="fa fa-check"></i><b>13.4</b> PSMに関する既存研究*</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html#受容価格に関する知見"><i class="fa fa-check"></i><b>13.4.1</b> 受容価格に関する知見</a></li>
<li class="chapter" data-level="13.4.2" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html#internal"><i class="fa fa-check"></i><b>13.4.2</b> 内的参照価格に関する知見</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="受容価格帯と内的参照価格帯の応用とpsm.html"><a href="受容価格帯と内的参照価格帯の応用とpsm.html"><i class="fa fa-check"></i><b>13.5</b> 受容価格帯と内的参照価格帯の応用とPSM</a></li>
<li class="chapter" data-level="13.6" data-path="集計方法に関する注意点.html"><a href="集計方法に関する注意点.html"><i class="fa fa-check"></i><b>13.6</b> 集計方法に関する注意点</a></li>
<li class="chapter" data-level="13.7" data-path="練習問題-8.html"><a href="練習問題-8.html"><i class="fa fa-check"></i><b>13.7</b> 練習問題</a></li>
<li class="chapter" data-level="13.8" data-path="参考文献-11.html"><a href="参考文献-11.html"><i class="fa fa-check"></i><b>13.8</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="consumer.html"><a href="consumer.html"><i class="fa fa-check"></i><b>14</b> コラム1（消費者行動研究の系譜概観）</a>
<ul>
<li class="chapter" data-level="14.1" data-path="参考文献-12.html"><a href="参考文献-12.html"><i class="fa fa-check"></i><b>14.1</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="causation1.html"><a href="causation1.html"><i class="fa fa-check"></i><b>15</b> コラム2-1（マーケティングにおける因果推論導入）</a>
<ul>
<li class="chapter" data-level="15.1" data-path="参考文献-13.html"><a href="参考文献-13.html"><i class="fa fa-check"></i><b>15.1</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="causation2.html"><a href="causation2.html"><i class="fa fa-check"></i><b>16</b> コラム2-2（ランダム化比較試験とカゴ落ちメール）</a>
<ul>
<li class="chapter" data-level="16.1" data-path="ランダム化比較試験概要.html"><a href="ランダム化比較試験概要.html"><i class="fa fa-check"></i><b>16.1</b> ランダム化比較試験概要</a></li>
<li class="chapter" data-level="16.2" data-path="li-et-al.-2021-によるカゴ落ちメールに関するフィールド実験.html"><a href="li-et-al.-2021-によるカゴ落ちメールに関するフィールド実験.html"><i class="fa fa-check"></i><b>16.2</b> Li et al. (2021) によるカゴ落ちメールに関するフィールド実験</a></li>
<li class="chapter" data-level="16.3" data-path="参考文献-14.html"><a href="参考文献-14.html"><i class="fa fa-check"></i><b>16.3</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="causation3.html"><a href="causation3.html"><i class="fa fa-check"></i><b>17</b> コラム3（非遵守と操作変数法）</a>
<ul>
<li class="chapter" data-level="17.1" data-path="操作変数法の概要.html"><a href="操作変数法の概要.html"><i class="fa fa-check"></i><b>17.1</b> 操作変数法の概要</a></li>
<li class="chapter" data-level="17.2" data-path="complier.html"><a href="complier.html"><i class="fa fa-check"></i><b>17.2</b> 実験非遵守における操作変数法の活用</a></li>
<li class="chapter" data-level="17.3" data-path="参考文献-15.html"><a href="参考文献-15.html"><i class="fa fa-check"></i><b>17.3</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="causation4.html"><a href="causation4.html"><i class="fa fa-check"></i><b>18</b> コラム4（パネルデータと固定効果：差の差の分析法準備）</a>
<ul>
<li class="chapter" data-level="18.1" data-path="データのタイプ-1.html"><a href="データのタイプ-1.html"><i class="fa fa-check"></i><b>18.1</b> データのタイプ</a></li>
<li class="chapter" data-level="18.2" data-path="パネルデータ分析と固定効果.html"><a href="パネルデータ分析と固定効果.html"><i class="fa fa-check"></i><b>18.2</b> パネルデータ分析と固定効果</a></li>
<li class="chapter" data-level="18.3" data-path="chief-marketing-officerの影響に関する分析.html"><a href="chief-marketing-officerの影響に関する分析.html"><i class="fa fa-check"></i><b>18.3</b> Chief Marketing Officerの影響に関する分析</a></li>
<li class="chapter" data-level="18.4" data-path="参考文献-16.html"><a href="参考文献-16.html"><i class="fa fa-check"></i><b>18.4</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="causation5.html"><a href="causation5.html"><i class="fa fa-check"></i><b>19</b> コラム5（差の差の分析法）</a>
<ul>
<li class="chapter" data-level="19.1" data-path="fisher-et-al.-2019-による配送能力と小売成果の研究.html"><a href="fisher-et-al.-2019-による配送能力と小売成果の研究.html"><i class="fa fa-check"></i><b>19.1</b> Fisher et al. (2019) による配送能力と小売成果の研究</a></li>
<li class="chapter" data-level="19.2" data-path="参考文献-17.html"><a href="参考文献-17.html"><i class="fa fa-check"></i><b>19.2</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="コラム-wide型とlong型データセット.html"><a href="コラム-wide型とlong型データセット.html"><i class="fa fa-check"></i><b>20</b> コラム： Wide型とLong型データセット</a></li>
<li class="chapter" data-level="21" data-path="コラム研究課題理論質問項目の作成.html"><a href="コラム研究課題理論質問項目の作成.html"><i class="fa fa-check"></i><b>21</b> コラム：研究課題・理論・質問項目の作成</a>
<ul>
<li class="chapter" data-level="21.1" data-path="参考文献-18.html"><a href="参考文献-18.html"><i class="fa fa-check"></i><b>21.1</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="コラム分析結果のまとめ出力上の工夫.html"><a href="コラム分析結果のまとめ出力上の工夫.html"><i class="fa fa-check"></i><b>22</b> コラム：分析結果のまとめ・出力上の工夫</a></li>
<li class="chapter" data-level="23" data-path="pcafa.html"><a href="pcafa.html"><i class="fa fa-check"></i><b>23</b> コラム：主成分分析と因子分析との違い</a>
<ul>
<li class="chapter" data-level="23.1" data-path="参考文献-19.html"><a href="参考文献-19.html"><i class="fa fa-check"></i><b>23.1</b> 参考文献</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">マーケティングリサーチの進め方</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="重回帰モデル" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> 重回帰モデル<a href="重回帰モデル.html#重回帰モデル" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>本章のこれまでの内容では、回帰分析の概要や係数の検定・推定について説明した。回帰分析を実行することで得る情報は前節の内容がほとんどなのだが、モデルの特定化に関して、もう一つ重要な点が存在する。それが本節で扱う重回帰モデル（multiple regression model）の採用である。重回帰モデルとは、二つ以上の説明変数を含む回帰モデルのことである。一方で、前節で扱ったような説明変数が一つの回帰モデルのことを単回帰（simple regression model）という。回帰分析を用いた研究を行う際には、基本的に単回帰分析ではなく、重回帰分析を実行することが好ましい。通常の分析においては、ある被説明変数に対して考慮すべき説明変数は一つだけではなく、複数の説明変数を考慮すべき状況が多い。しかし、分析に不慣れ学生においては、複数の説明変数に関心がある場合であっても、複数の単回帰モデルを分析することで、それぞれの変数についての分析結果を得ようとすることが散見される（例えば、三つの説明変数の影響を捉えるために単回帰モデルを三本分析する等）。しかしながら本書は、基本的にはこのような分析アプローチは好ましくなく、複数の説明変数を含めた一本の重回帰分析を実施すべきだと主張する。本節では、この主張の理由と、重回帰モデルの特徴・結果解釈について説明していく。</p>
<div id="重回帰モデル概要" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> 重回帰モデル概要<a href="重回帰モデル.html#重回帰モデル概要" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ある成果変数を説明するために、複数の説明変数が必要になることは、マーケティングリサーチにおいても珍しいことではない。例えば、ある製品のパフォーマンスを月次売上高で測るとする。マーケティング部門として、売上高に対してプロモーション施策がどれだけ貢献しているかを分析する際、プロモーションと売上高の関係を回帰分析で捉えるというアプローチが実現可能な分析方法として考えられる。</p>
<p>しかしながら、売上高を説明する変数はプロモーションだけで十分だろうか。マーケティング変数に着目するだけでも、価格や製品品質、流通網など、異なる変数が売上に関係していることが考えられる。例えば、一見プロモーションによる効果のような結果を得たとしても、実際にその製品の価格による影響であり、プロモーションそのものにはあまり効果がないかもしれない。そのため、他の要素の影響を排除した上での純粋なプロモーション効果を明らかにすることは実務的に有意義な研究課題となりうる。そしてこのような研究課題に対応する分析方法が、重回帰分析である。</p>
<div class="float">
<img src="reg/fig1.png" style="width:70.0%" alt="売上とマーケティング変数" />
<div class="figcaption">売上とマーケティング変数</div>
</div>
</div>
<div id="重回帰モデルの記述と性質" class="section level3 hasAnchor" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> 重回帰モデルの記述と性質<a href="重回帰モデル.html#重回帰モデルの記述と性質" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>重回帰分析においても単回帰同様、回帰モデルを記述することができる。<em>k</em> 個の説明変数を含む重回帰モデルは、以下のように示される。</p>
<p><span class="math display">\[
y_i = \beta_0+\beta_1x_{1i}+\beta_2x_{2i}+...+\beta_kx_{ki}+u_i
\]</span></p>
<p>論文やレポート内に重回帰モデルを記載する際にも、多くの場合上記の誤差項を含む理論モデルを用いる。</p>
<p>以下ではまず、重回帰モデルの係数、予測値や、残差に関する性質について説明する。重回帰分析を実行すると、各説明変数に対応する係数が推定される。各OLSE（<span class="math inline">\(\small \hat{\beta}\)</span>）は 未知パラメータ（<span class="math inline">\(\small \beta\)</span>）の不偏推定量である。また、それらの検定や区間推定では、各変数に対応する係数の検定・推定を個別に行う。OLS推定に関わる残差と予測値はそれぞれ以下のように意義される。</p>
<ul>
<li><p>予測値:
<span class="math display">\[
\hat{y}_i = \hat{\beta}_0+\hat{\beta}_1x_{1i}+\hat{\beta}_2x_{2i}+...+\hat{\beta}_kx_{ki}
\]</span></p></li>
<li><p>残差:
<span class="math display">\[
\hat{u}_i=y_i-\hat{y}_i =y-( \hat{\beta}_0+\hat{\beta}_1x_{1i}+\hat{\beta}_2x_{2i}+...+\hat{\beta}_kx_{ki})
\]</span>
そして、残差は以下の <span class="math inline">\(k+1\)</span> 個の制約を満たす。</p></li>
<li><p><span class="math inline">\(\sum_{i=1}^n\hat{u}_i=0\)</span></p></li>
<li><p><span class="math inline">\(\sum_{i=1}^n x_{1i}\hat{u}_i=0,~\sum_{i=1}^nx_{2i}\hat{u}_i=0...,~\sum_{i=1}^nx_{ki}\hat{u}_i=0\)</span></p></li>
</ul>
<p>そのため、重回帰モデルの残差の自由度は <span class="math inline">\(n-(k+1)\)</span> となる。</p>
</div>
<div id="重回帰分析におけるモデル適合度" class="section level3 hasAnchor" number="7.5.3">
<h3><span class="header-section-number">7.5.3</span> 重回帰分析におけるモデル適合度<a href="重回帰モデル.html#重回帰分析におけるモデル適合度" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>単回帰モデルにおけるモデル適合度指標として前節では決定係数を紹介した。しかしながら、この指標は致命的な欠陥を有している。それは、モデルに含む説明変数の数が増えると決定係数も上昇する（より正確には、説明変数の数に対して非減少）ということである。つまり、被説明変数と全く関係ない変数をモデルに加えても、決定係数は上昇し、そのモデルの説明力が高いという結論に至ってしまう。そのため、通常の決定係数から説明変数の数を調整した指標である調整済み決定係数（Adjusted R-squared: <span class="math inline">\(\bar{R}^2\)</span>）を用いて適合度を検討する。この指標は、以下のように定義される。</p>
<p><span class="math display">\[
\bar{R}^2= 1 - \left(\frac{\sum(y_i-\hat{y}_i)}{n-k-1}\cdot \frac{n-1}{\sum(y_i-\bar{y})}\right)
\]</span></p>
<p>モデルの適合度を考えるもう一つの分析として、Rの分析結果で出力されていたF検定について説明する。回帰分析の結果として必ず出力されるF検定は、重回帰モデルにおける<span class="math inline">\(\small \beta_0\)</span>（定数項） 以外の係数が全て0であるか否かをチェックする検定である。この検定では、k個の説明変数を含む回帰モデル（<span class="math inline">\(\small y_i = \beta_0+\beta_1x_{1i}+\beta_2x_{2i}+...+\beta_kx_{ki}+u_i\)</span>）に対して（これをフルモデルと呼ぶ）、以下のような帰無仮説と対立仮説を用いた検定を行う。</p>
<p><span class="math display">\[
H_0:~\beta_1=...=\beta_k=0,~H_1:\text{少なくともどれか一つの係数は0ではない}
\]</span>
帰無仮説が正しいと仮定した場合、重回帰モデルは以下のようになり、この定数項のみのモデルをモデル0と呼ぶ。</p>
<p><span class="math display">\[
y_i = \beta_0+e_i
\]</span></p>
<p>そして、フルモデルとモデル0の残差平方和の比を取った統計量は、帰無仮説が正しいときには自由度（<span class="math inline">\(k,~n-k-1\)</span>）の F分布に従うことが知られている。この性質を活かし、回帰分析においては自由度（<span class="math inline">\(k,~n-k-1\)</span>）のF分布を前提とした統計検定を行い、それをF検定（F-test）と呼ぶ。回帰分析結果にて出力される <code>F-statistic:</code>は、この検定統計量の実現値である。なお、この検定の検定統計量は、以下のように示される。</p>
<p>フルモデルとモデル0の残差平方和（<span class="math inline">\(SSR_1\)</span>と<span class="math inline">\(SSR_0\)</span>）をそれぞれ以下のように定義する。</p>
<ul>
<li><p><span class="math inline">\(SSR_1=\sum\hat{u}^2_i=\sum\left[y-( \hat{\beta}_0+\hat{\beta}_1x_{1i}+\hat{\beta}_2x_{2i}+...+\hat{\beta}_kx_{ki})\right]^2\)</span></p></li>
<li><p><span class="math inline">\(SSR_0=\sum\hat{e}^2_i=\sum(y_i-\bar{y})^2\)</span></p></li>
</ul>
<p>そして、以下の統計量 <em>F</em> は帰無仮説が正しければ、自由度（<span class="math inline">\(k,~n-k-1\)</span>）の F分布に従うことが知られているため、これを検定統計量として用いて検定を行う。</p>
<p><span class="math display">\[
F=\frac{(SSR_0-SSR_1)/k}{SSR_1/(n-k-1)}=\frac{SSR_0-SSR_1}{SSR_1}\cdot\frac{n-k-1}{k}
\]</span></p>
</div>
<div id="回帰係数の解釈" class="section level3 hasAnchor" number="7.5.4">
<h3><span class="header-section-number">7.5.4</span> 回帰係数の解釈<a href="重回帰モデル.html#回帰係数の解釈" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>ここからは、重回帰分析の係数の解釈について説明する。ここで説明する解釈は「なぜ基本的には重回帰モデルを採用すべきなのか」を理解するために重要な内容である。結論から述べると、重回帰分析における説明変数の係数は、「説明変数が持つ変動のうち他の説明変数とは無関係な変動だけを抽出し、被説明変数との関係を分析している」と解釈できる。この特徴が、同モデル内の「他の変数の影響をコントロールしたうえで」説明変数が被説明変数へ与える影響を捉える方法として、学術的にも実務的にも活用されている。</p>
<p>重回帰モデルにおける各説明変数の係数は、パーシャル効果として解釈できる。以下では、このパーシャル効果の直感について、Wooldridge（2013）を参考に説明する。まず、以下のような説明変数が二個である重回帰モデルを考える。</p>
<p><span class="math display">\[
y_i=\beta_0+\beta_1x_{1i}+\beta_2x_{2i}+u
\]</span>
そして、上モデルの予測値は以下のように示すことができる。</p>
<p><span class="math display">\[
\hat{y}_i=\hat{\beta}_0+\hat{\beta}_1x_{1i}+\hat{\beta}_2x_{2i}
\]</span></p>
<p>このとき、説明変数 <span class="math inline">\(\small x_1\)</span> と <span class="math inline">\(\small x_2\)</span> の変化をそれぞれ、 <span class="math inline">\(\small \Delta x_{1i}\)</span> と <span class="math inline">\(\small \Delta x_{2i}\)</span> とすると、予測値の変化（<span class="math inline">\(\small \Delta \hat{y}\)</span>）は以下のように表すことができる。</p>
<p><span class="math display">\[
\Delta\hat{y}_i=\hat{\beta}_1\Delta x_{1i}+\hat{\beta}_2\Delta x_{2i}
\]</span></p>
<p>ここで、<span class="math inline">\(\small x_2\)</span> を固定（<span class="math inline">\(\small \Delta x_{2i}=0\)</span>）すると、以下を得る。</p>
<p><span class="math display">\[
\Delta\hat{y}_i=\hat{\beta}_1\Delta x_{1i}
\]</span>
つまり、重回帰モデルにおける <span class="math inline">\(\hat{\beta}_1\)</span> は、別の説明変数をコントロール（<span class="math inline">\(\small \Delta x_{2i}=0\)</span>）した上で、<span class="math inline">\(\small x_1\)</span> が <span class="math inline">\(\small \hat{y}\)</span> に与える影響（<span class="math inline">\(\small x_1\)</span> が変化した際の <span class="math inline">\(\small \hat{y}\)</span>の変化の程度）を捉えていると解釈できる。また、<span class="math inline">\(\small \hat{\beta}_2\)</span> についても同様に解釈できる。そしてこの特徴は、<em>k</em>個の説明変数を用いたモデルにも同様に適応できる。</p>
<p><span class="math inline">\(x_{2}\)</span> を固定すると上では述べたが、このような分析を行った際の<span class="math inline">\(x_1\)</span> と <span class="math inline">\(\beta_1\)</span> については具体的にどのような変動・効果を捉えているのだろうか。以下では、パーシャル効果についてもう少し詳細に説明することで、係数の解釈についての理解を深める。先ほど重回帰モデルの回帰係数は、「説明変数が持つ変動のうち他の説明変数とは無関係な変動だけを抽出し、被説明変数との関係を分析している」と述べた。この点を理解するために、次の2つの説明変数を含む回帰モデルを考える。</p>
<p><span class="math display">\[
y_i = \hat{\beta}_0 + \hat{\beta}_1 x_{i1} +\hat{\beta}_2 x_{i2}+\hat{u}_i = \hat{y_i} + \hat{u}_i
\]</span></p>
<p>このとき、変数 <span class="math inline">\(x_{i1}\)</span> と <span class="math inline">\(x_{i2}\)</span> の関係は次のように表される。</p>
<p><span class="math display">\[
x_{i1} = \hat{\gamma}_0 + \hat{\gamma}_2 x_{i2} +\hat{r}_{i1} = \hat{x}_{i1} + \hat{r}_{i1}
\]</span></p>
<p>ここで、<span class="math inline">\(\hat{r}_{i1}\)</span> は、<span class="math inline">\(x_1\)</span> を <span class="math inline">\(x_2\)</span> に対して単回帰したときの OLS 残差を表す。つまり、<span class="math inline">\(\hat{r}_{i1}\)</span> は <span class="math inline">\(x_{i1}\)</span> のうち、<span class="math inline">\(x_{i2}\)</span> と無相関な部分である。これらを総合すると<span class="math inline">\(x_{1}\)</span> の変動は、別の説明変数 <span class="math inline">\(x_{2}\)</span> との関係で説明できる部分（変動：<span class="math inline">\(\hat{x}_{1}\)</span>）と、<span class="math inline">\(x_{2}\)</span> とは無関係な部分（<span class="math inline">\(\hat{r}_{1}\)</span>）とに分けて捉えることができる。</p>
<p>上の式に基づき、<span class="math inline">\(\hat{x}_{i1}\)</span> と <span class="math inline">\(\hat{u_i}\)</span> の関係について以下を得る。</p>
<p><span class="math display">\[
\sum \hat{x}_{i1} \hat{u_i} = \sum (\hat{x}_{i1} + \hat{r}_{i1})\hat{u}_i = \sum \hat{x}_{i1}\hat{u}_i + \sum \hat{r}_{i1}\hat{u}_i = 0.
\]</span></p>
<p>次に、<span class="math inline">\(\sum \hat{x}_{i1}\hat{u}_i\)</span> は以下のように書き換えられる。</p>
<p><span class="math display">\[
\sum \hat{x}_{i1}\hat{u}_i = \sum (\hat{\gamma}_0 +\hat{\gamma}_2 x_{i2})\hat{u}_i = \hat{\gamma}_0 \underbrace{\sum \hat{u}_i}_{0} + \hat{\gamma}_2 \underbrace{\sum x_{i2}\hat{u}_i}_{0} = 0
\]</span></p>
<p>したがって、<span class="math inline">\(\sum \hat{r}_{i1}\hat{u}_i\)</span> は以下を満たすはずである。</p>
<p><span class="math display">\[
\begin{aligned}
\sum \hat{r}_{i1}\hat{u}_i =
\sum\hat{r}_{i1}(y_i -\hat{\beta}_0 - \hat{\beta}_1 x_{i1} - \hat{\beta}_2 x_{i2})\\
= \sum \hat{r}_{i1} y_i -\hat{\beta}_0 \underbrace{\sum \hat{r}_{i1}}_{0} - \hat{\beta}_1 \sum \hat{r}_{i1} x_{i1} - \hat{\beta}_2 \underbrace{\sum \hat{r}_{i1} x_{i2}}_{0}\\
= \sum \hat{r}_{i1} y_i - \hat{\beta}_1 \sum \hat{r}_{i1} x_{i1} = 0
\end{aligned}
\]</span></p>
<p>よって、<span class="math inline">\(\hat{\beta}_1\)</span> は次のように表される。</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{\sum \hat{r}_{i1} y_i}{\sum \hat{r}_{i1} x_{i1}}=\frac{\sum \hat{r}_{i1} y_i}{\sum \underbrace{\hat{r}_{i1}(\hat{x}_{i1}}_{0} + \hat{r}_{i1})}=\frac{\sum \hat{r}_{i1} y_i}{\sum \hat{r}_{i1}^2}
\]</span></p>
<p>上記の議論に基づき、<span class="math inline">\(\hat{\beta}_1\)</span> は <span class="math inline">\(x_2\)</span> の影響を取り除いた後の <span class="math inline">\(y\)</span> と <span class="math inline">\(x_1\)</span> の関係を示すと解釈できる。この関係を用い、回帰係数の解釈に対するイメージは以下のように示すことができる。下図の（1）は単回帰モデルによって <span class="math inline">\(x_1\)</span> と <span class="math inline">\(x_2\)</span> が持つ<span class="math inline">\(y\)</span> との関係を捉えた構造をイメージしたものであり、（2）は重回帰モデルの係数についてのイメージを捉えたものである。（2）では、<span class="math inline">\(x_1\)</span> と <span class="math inline">\(x_2\)</span> の重複部分（相関）を取り除いた <span class="math inline">\(\hat{r}_1\)</span> と <span class="math inline">\(\hat{r}_2\)</span> それぞれと <span class="math inline">\(y\)</span> の関係を捉えていることが伺える。コントロール変数の採用は便利ではあるが、自身が重回帰モデルを採用する際には、どのような条件で変数の効果を捉えているのかについて、モデルに含まれる変数同士の関係から検討する必要がある。特に、<a href="重回帰モデル.html#varsel">7.5.6</a> で論じる
過剰統制の問題については慎重に考える必要がある。</p>
<div class="float">
<img src="reg/coef_image.png" style="width:70.0%" alt="回帰係数イメージ" />
<div class="figcaption">回帰係数イメージ</div>
</div>
</div>
<div id="単回帰モデルと重回帰モデルの比較" class="section level3 hasAnchor" number="7.5.5">
<h3><span class="header-section-number">7.5.5</span> 単回帰モデルと重回帰モデルの比較<a href="重回帰モデル.html#単回帰モデルと重回帰モデルの比較" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>では、このパーシャル効果という重回帰モデルの特徴は、どのように応用できるのだろうか。多くの実証研究では、重回帰モデルの特徴を利用し、「コントロール変数」を用いた分析を行っている。本節では、先程の企業データを用いて、「企業の広告支出が営業利益に与える影響を明らかにする」という問いを考える。まずは、学習的意図から以下のように単回帰分析を実施してみる（通常の論文・レポートであればこのような過程は必要ない）。</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="重回帰モデル.html#cb176-1" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(operating_profit <span class="sc">~</span> adv, <span class="at">data =</span> firmdata19)</span>
<span id="cb176-2"><a href="重回帰モデル.html#cb176-2" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = operating_profit ~ adv, data = firmdata19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -450515  -55314  -40160   -1096  599313 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 5.685e+04  1.050e+04   5.414 2.49e-07 ***
## adv         1.258e+00  2.152e-01   5.846 3.20e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 117200 on 145 degrees of freedom
## Multiple R-squared:  0.1907, Adjusted R-squared:  0.1852 
## F-statistic: 34.18 on 1 and 145 DF,  p-value: 3.197e-08</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="重回帰モデル.html#cb178-1" tabindex="-1"></a><span class="fu">confint</span>(reg2)</span></code></pre></div>
<pre><code>##                    2.5 %       97.5 %
## (Intercept) 3.609692e+04 77602.573216
## adv         8.325719e-01     1.683065</code></pre>
<p>分析の結果、広告支出（<code>adv</code>）の係数は正に有意であり、その95%信頼区間は [0.83, 1.68] であることが確認できた（8.325719e-01は0.8325719）。</p>
<p>しかしながら、このモデル化は不十分であり他の要素も考慮すべきである。営業利益に影響を与えうる要因は色々とあり
、実際の研究においては先行研究を参照しつつ、コントロールすべき変数を含める形で回帰モデルを特定する必要がある。しかしながら、ここでは便宜上いくつかの要因にのみ焦点を合わせて簡単に特定化する。本データは主に小売・サービス産業の企業に焦点を合わせている。そのため、対人サービス水準は企業のパフォーマンスに影響を与えうる要因である。そのため、従業員に関する変数（従業員数: emp、パートタイム従業員数: temp）と人件費（labor_cost）をモデルに含める。また、資産合計（total_assets）、研究開発費（rd）もモデルに含める。今回の回帰モデルは以下のように示される。</p>
<p><span class="math display">\[
\text{opretating_profit}_i = \beta_0 + \beta_1 adv_i + \beta_2emp_i+\beta_3temp_i+\beta_4\text{labor_cost}_i+\beta_5\text{total_assets}_i+\beta_6rd_i+u_i
\]</span>
Rにおいて重回帰分析を実行するのは簡単である。<code>lm(y ~ x1 + x2 + x3)</code> のように <span class="math inline">\(+\)</span> 記号と変数を追加すれば、重回帰モデルとして分析を実行してくれる。</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="重回帰モデル.html#cb180-1" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(operating_profit <span class="sc">~</span> adv <span class="sc">+</span> temp <span class="sc">+</span> emp <span class="sc">+</span> labor_cost <span class="sc">+</span> total_assets <span class="sc">+</span> rd, <span class="at">data =</span> firmdata19)</span>
<span id="cb180-2"><a href="重回帰モデル.html#cb180-2" tabindex="-1"></a><span class="fu">summary</span>(reg3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = operating_profit ~ adv + temp + emp + labor_cost + 
##     total_assets + rd, data = firmdata19)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -360570  -27367  -14970    3349  284990 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.168e+04  8.056e+03   2.691  0.00800 ** 
## adv          -1.430e+00  2.946e-01  -4.852 3.22e-06 ***
## temp         -1.866e+00  6.292e-01  -2.965  0.00356 ** 
## emp          -1.489e+00  7.008e-01  -2.125  0.03533 *  
## labor_cost    8.770e-01  1.686e-01   5.202 6.86e-07 ***
## total_assets  3.507e-02  5.823e-03   6.023 1.43e-08 ***
## rd            1.380e+00  5.254e-01   2.627  0.00957 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 78740 on 140 degrees of freedom
## Multiple R-squared:  0.6474, Adjusted R-squared:  0.6323 
## F-statistic: 42.84 on 6 and 140 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="重回帰モデル.html#cb182-1" tabindex="-1"></a><span class="fu">confint</span>(reg3)</span></code></pre></div>
<pre><code>##                      2.5 %        97.5 %
## (Intercept)  5749.50978947  3.760568e+04
## adv            -2.01201729 -8.470087e-01
## temp           -3.10966464 -6.216177e-01
## emp            -2.87467416 -1.038058e-01
## labor_cost      0.54369783  1.210293e+00
## total_assets    0.02355591  4.657974e-02
## rd              0.34159701  2.419018e+00</code></pre>
<p>見ての通り、結果の出力方式そのものは単回帰分析のものとほぼ同様である。回帰係数の結果下にあるモデル適合度については前節を参照して欲しい。</p>
<p>分析の結果、広告支出の係数は「負」に有意であり、その信頼区間も [-2.01, -0.84] であった。したがって、本データの分析によると、労働や資産に加え研究開発といった側面を一定とすると、広告支出は営業利益に対して負の関係を持っていることがわかった。他の変数に着目すると、従業員数に関する変数はどちらも負に有意であった。一方で、人件費と総資産、研究開発費は正に有意な影響を与えることが示された。これらの結果から、単純に従業員数を増やしても営業利益には負の影響を与える一方で、従業員数を一定とした上で人件費を上げるほうが営業利益が高いことが示された。また、資産や研究開発費も営業利益につながることが示された。</p>
<p>このように、重回帰モデルを採用し複数の説明変数を含めることで、各係数の持つ含意が大きく変わることに注意して欲しい。また、<code>reg2</code> と <code>reg3</code>の比較のように、特定の説明変数に対応する係数の符号が変わることも珍しくない。そのため、回帰モデルの定式化には非常に慎重になる必要があり、先述の通り、先行研究を参照して必要な変数をコントロールすることが求められる。</p>
<p>また、これらの結果を踏まえて、<a href="design.html#design">3</a>章で強調した「マネジメントとリサーチの分離」の重要性を思い出して欲しい。あなたが <code>reg2</code> と <code>reg3</code>の分析を実施したリサーチャーであり、本リサーチのクライアントがマーケティング・広告部門の部長だっとしよう。そして、（1）あなた自身もマーケティング部門の社員であり、クライアントは直属の上司、（2）あなた自身はクライアントとは無関係の立場、という二つの異なる立場に立っている状況を想像して欲しい。（1）の場合、逆恨みによるあなた自身への不利益を恐れて重回帰分析の結果を「ありのまま」伝えられないかもしれない。もちろん研究倫理に基づけば、都合の良い研究成果を作為的に発表することは問題であり、そのようなことはすべきではない。しかしながら、その背後にある利害関係を鑑みれば、<code>reg2</code>
の結果を報告したくなる人がいることも理解できる。個人の判断を批判するだけでなく、このような研究不正を働く誘因や構造についても考慮すべきである。なお、定量的な分析に慣れている研究者にとっては、特別な理由がないにも関わらず単回帰分析の結果のみを伝えることは不自然な分析アプローチである。そのため、 もし調査・分析の設計上意図的に単回帰分析を実施する場合には、その意図と有用性をきちんと説明する必要がある。</p>
</div>
<div id="varsel" class="section level3 hasAnchor" number="7.5.6">
<h3><span class="header-section-number">7.5.6</span> 重回帰モデルにおける変数選択<a href="重回帰モデル.html#varsel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>重回帰モデルでは、複数の説明変数を採用することができるため、どの変数をモデルに含めるべきかという点を考察しモデルを特定化する必要がある。このような説明変数の選択に関わる問題として、本節では、欠落変数バイアス、多重共線性、過剰統制の三つを紹介する。</p>
<div id="欠落変数バイアス" class="section level4 hasAnchor" number="7.5.6.1">
<h4><span class="header-section-number">7.5.6.1</span> 欠落変数バイアス<a href="重回帰モデル.html#欠落変数バイアス" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>欠落変数バイアスは、本来含めるべき変数を含めずにモデルを定式化し推定を行った際に生じる、推定された係数に対するバイアスであり、これによりOLSEが不偏推定量でなくなるという問題が生じる。また、このバイアスの方向（正負）は欠落された変数と被説明変数との真の関係（欠落された変数が被説明変数に対して持つ母集団での回帰係数）と、モデルに含まれる説明変数と欠落変数との相関で決まる（Wooldridge, 2013）。以下で欠落変数バイアスについての簡単な説明を提示する。</p>
<p>はじめに、以下の式が正しいモデルだと仮定する。
<span class="math display">\[
y=\beta_0+\beta_1x_1+\beta_2x_2+u
\]</span>
これに対して<span class="math inline">\(x_2\)</span>を含まずに欠落変数モデルを推定した場合、以下のような結果を得る。</p>
<p><span class="math display">\[
\tilde{y}=\tilde{\beta}_0+\tilde{\beta}_1x_1
\]</span>
このとき、真のモデルの推定値（<span class="math inline">\(\small \hat{\beta}_1\)</span>）と <span class="math inline">\(\small \tilde{\beta}_1\)</span> の間には、以下の関係がある。</p>
<p><span class="math display">\[
\tilde{\beta}_1=\hat{\beta}_1+\hat{\beta_2}\tilde{\delta_1}
\]</span>
ただし、<span class="math inline">\(x2\)</span> を <span class="math inline">\(x_1\)</span>で回帰したモデルの予測値 <span class="math inline">\(\tilde{x}_2\)</span>は、<span class="math inline">\(\small \tilde{x}_2=\tilde{\delta}_0+\tilde{\delta}_1x_1\)</span>とする。つまり、<span class="math inline">\(\small \tilde{\delta}_1\)</span> は <span class="math inline">\(\small x_1\)</span> の <span class="math inline">\(\small x_2\)</span> に対する回帰係数の推定値である。したがって以下のように、欠落変数モデルでは推定結果に<span class="math inline">\(\small \beta_2\tilde{\delta}_1\)</span> の分だけバイアスが生じていると理解できる。</p>
<p><span class="math display">\[
E(\tilde{\beta}_1|x_1,x_2)=E(\hat{\beta}_1)+E(\hat{\beta_2} \tilde{\delta_1})=\beta_1+\beta_2\tilde{\delta}_1
\]</span>
そして、欠落変数によってバイアスが生じるということが、重回帰分析の重要性を主張する根拠となる。そのため、仮に研究課題上ではあまり重要でない変数であっても、自身の関心のある説明変数の影響を分析するためにコントロール変数をモデルに含めることが重要になる。</p>
</div>
<div id="多重共線性" class="section level4 hasAnchor" number="7.5.6.2">
<h4><span class="header-section-number">7.5.6.2</span> 多重共線性<a href="重回帰モデル.html#多重共線性" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>第二の論点として、単回帰分析の際には存在しなかった多重共線性（multicollinearity）という問題がある。これは説明変数同士の相関が高いことによる推定上の問題であり、Variance Inflation Factor という指標<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a>を使ってその程度を測ることもある。また、マーケティング領域の研究においてはまれに「多重共線性があるから、説明変数を除外すべきだ」という主張を聞くことがある。しかしながら、本書はできる限り説明変数の除外を行わないほうが良いという立場を提示する。詳しくは後述するが、分析の対象となる説明変数によって極端にVIFが高くなる場合には、次の段落にあるようにその変数の意義を検討し、その変数をそのまま残す、何かで比を取る、対数化する（詳しくは次章）などの変数変換の工夫をしながら、その変数をモデルに含めるということが現実的かつ実践的な対応となる。なおこの立場は、本書が回帰分析における係数の検証や解釈に注視していることに大きく依存するため、注意してほしい。</p>
<p>多重共線性について語る際には、(1) 説明変数同士が完全に相関している（相関係数が 1 もしくは -1）場合と、(2) 完璧ではないが相関係数が高い場合、という二つの異なる状況を区別し理解する必要がある。まず一つ目の場合、そもそも係数の推定値が計算できないという問題が生じる。そのため、完璧に相関しあっている変数を同時にモデルに含めることは出来ず、変数の除外を考えないといけない。この問題は言い換えると「同じ変数を同モデル内に複数入れてはいけない」という制約だと理解できる（西山ほか, 2019）。</p>
<p>一方で（2）の場合、説明変数同士の相関は、推定量の分散 <span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> を高めてしまう（Wooldridge, 2013）。しかし、 <span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> は、多重共線性だけでなく以下の三つの要素から影響を受ける。第一に、誤差項の真の分散（<span class="math inline">\(\small \sigma^2\)</span>）、第二に独立変数間の相関<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a>、第三に、独立変数の変動（<span class="math inline">\(\small SST_j=\sum(x_{ji}-\bar{x}_j)^2\)</span>）である。第一と第二の指標が高い場合には、推定量の分散は大きくなる。一方で、第三の要素である<span class="math inline">\(\small SST_j\)</span> が高い場合には <span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> は小さくなる。そのため、<span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> を改善するためには、サンプルサイズを大きくし<span class="math inline">\(\small SST_j\)</span> を大きくすることも有用な対処方法となる。しかしながら、社会科学分野においてはデータ取得可能性の観点からそれが難しいことも多い。そのときには、推定量分散の増加と説明変数除外による弊害とのトレードオフを考慮して意思決定することになる。</p>
<p>そのうえで本書は、先述の通りできる限り説明変数を除外することは避けるほうが良いという立場を取る。必要な説明変数を含めずに回帰分析を行うと、欠落変数バイアスの問題が生じる。また、もし分析における主な関心が、着目する説明変数 <span class="math inline">\(\small x_{ji}\)</span> の　<span class="math inline">\(y_{i}\)</span> への効果を検証・解釈することであり、かつそれをきちんと捉えるために他の説明変数をモデルに含めることが必要なのであれば、VIFは無視して構わない（cf. Wooldridge, 2013）。そのため、「VIFが10以上<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a>だから、多重共線性があり、変数を除外すべきだ」というような考えは、上記の研究上の関心に対しては恣意的であり有意義でないと考える。そもそも先述のように、VIFによって生じる問題は<span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> の増加であるが、この分散は他の要素にも影響を受けるため、VIFが10以上だから必ず <span class="math inline">\(\small Var(\hat{\beta}_j)\)</span> が大きすぎて推定量が有用でないということはない。これらのことから、回帰モデルに含む変数選択は、VIFの値に依存して判断するよりも、分析モデルの意図や用いる変数の理論的・分析的意義について検討し決断されるべきものだと考える。</p>
</div>
<div id="過剰制御" class="section level4 hasAnchor" number="7.5.6.3">
<h4><span class="header-section-number">7.5.6.3</span> 過剰制御<a href="重回帰モデル.html#過剰制御" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>第三に過剰制御（過剰コントロール）は、モデル内での係数解釈の変化を捉えた問題である。ここまでの説明では、欠落変数バイアスの議論を中心に、基本的には変数をモデルに含めることの重要性を説明してきた。しかしながら、重回帰分析の係数の解釈（パーシャル効果）を鑑みると、主要な説明変数の効果に関する理論的なメカニズムにおいて中間経路として機能する変数をモデルに含めることには注意が必要である。</p>
<p>例えば、製品開発におけるクラウドソーシングという非専門家（一般消費者）の意見を製品開発に活用する戦略（e.g., Nishikawa et al., 2017）が製品の売上に与える影響を、製品レベルデータを用いて分析する場合を考える。その際、クラウドソーシングの有効性に関するメカニズムとして、実際の製品ユーザーである消費者の意見を反映することで、品質の高い製品を開発でき、結果として売上向上につながるというものを考えているとする。つまり、クラウドソーシングが売上に与える中間経路として、製品の品質が機能するというメカニズムを考えていることになる。しかしながら、売上を被説明変数とする回帰モデルを考える際に、製品品質も売上に影響を与えうる変数なので説明変数として回帰モデルに含めたいと考えるかもしれない。このような考えが、過剰制御の問題につながる。製品品質は、クラウドソーシングから売上への影響に関する中間経路として機能する変数であり、クラウドソーシングがなぜ売上に影響するのかという理屈の中核を成す非常に重要な要因であった。これをコントロールしてしまうことは、クラウドソーシングの係数の解釈を大きく変えてしまう。具体的には、このようなモデルでは、製品品質を一定とした上でクラウドソーシングが売上に与える影響を捉えることになってしまう。上記の関係は以下の図のように示される。</p>
<div class="float">
<img src="reg/overcontrol.png" style="width:70.0%" alt="クラウドソーシングと売上の中間経路（品質）" />
<div class="figcaption">クラウドソーシングと売上の中間経路（品質）</div>
</div>
<p>製品品質以外のクラウドソーシングの効果が研究の関心と整合的であるならば、品質を含めた定式化で問題はない。しかしながら、重回帰モデルの変数選択では、自身が論じているメカニズムと係数解釈の整合性を保つように、中間経路変数を含めることで過剰制御の問題に陥っていないかを慎重に検討する必要がある。</p>
<p>重回帰モデルに含める変数の指針について、西山ほか（2019, p.186）は以下の表のように整理している。なお、本書においては主に欠落変数バイアスと係数の解釈という観点から変数選択に関する考え方を整理した。これは、研究上関心のある変数の効果（係数）について検証・解釈するという観点に基づく議論である。しかしながら、「予測」という側面に着目すれば推定や予測の精度を高める（誤差を小さくする）ことが重要になり、変数選択の基準も変わる。そうなれば、欠落変数による問題や係数の解釈の変化はあまり重要でなくなるかもしれない。このように、立場が変わることによって回帰モデルの特定化の基準も変化することを最後に付け加えておく。</p>
<table>
<caption><span id="tab:variablechoice">Table 7.1: </span>変数選択の指針</caption>
<colgroup>
<col width="12%" />
<col width="37%" />
<col width="15%" />
<col width="34%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">x に影響を与える or x と同時決定</th>
<th align="center">x から影響を受ける</th>
<th align="center">x とは無相関</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">y に影響を直接与える</td>
<td align="center">必ず含める（欠落変数を防ぐ）</td>
<td align="center">含めていけない（過剰制御）</td>
<td align="center">含めることで推定誤差は減る（含めなくてもバイアスは増えない）</td>
</tr>
<tr class="even">
<td align="center">y に影響を与えない</td>
<td align="center">含めないほうが良い（ただし推定誤差は増えるがバイアスは増えない）</td>
<td align="center">左と同様</td>
<td align="center">左と同様</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="19">
<li id="fn19"><p>後述する <span class="math inline">\(\small R^2_{j}\)</span> を用いて、<span class="math inline">\(VIF_j=1/(1-R^2_{j})\)</span> と定義される。<a href="重回帰モデル.html#fnref19" class="footnote-back">↩︎</a></p></li>
<li id="fn20"><p>より具体的には説明変数 <span class="math inline">\(x_{ji}\)</span>を従属変数に、その他の全ての説明変数を独立変数として回帰分析をした際の決定係数 <span class="math inline">\(R^2_j\)</span>、。なお、先述のVIFはこの<span class="math inline">\(R^2_j\)</span>の関数である。<a href="重回帰モデル.html#fnref20" class="footnote-back">↩︎</a></p></li>
<li id="fn21"><p>慣習としてよく用いられる閾値<a href="重回帰モデル.html#fnref21" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="回帰分析における推定と検定.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="練習問題-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/06-reg.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
